// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "The Rosebean",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "C:\\Users\\steve\\Downloads\\cafe-heros\\rosebean-cafe.webp",
  "aboutQuote": "We opened The Rosebean to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "07713 114230",
  "email": "dhcoffeehouse@gmail.com",
  "address": [
    "13d riverside crescent",
    "edinburgh"
  ]
};
